// ============================================================================
// Waiver PDF Generation Utility
// ============================================================================
// Destination: src/lib/generate-waiver-pdf.ts
// Dependency: npm install jspdf
// ============================================================================

import jsPDF from 'jspdf';

export interface WaiverPDFData {
  tenantName: string;
  tenantAccentColor?: string;
  tenantLogoUrl?: string;       // Supabase storage URL for tenant logo
  clientName: string;
  clientEmail?: string;
  clientPhone?: string;
  waiverText: string;
  signatureDataUrl: string;     // base64 PNG from signature canvas
  signedAt: string;              // ISO timestamp
  eventName?: string;
}

// Margins and layout constants (in points, 72pt = 1 inch)
const MARGIN_LEFT = 72;
const MARGIN_RIGHT = 72;
const MARGIN_TOP = 72;
const MARGIN_BOTTOM = 72;
const PAGE_WIDTH = 612;  // Letter width in points
const PAGE_HEIGHT = 792; // Letter height in points
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;

/**
 * Parse a hex color to RGB values for jsPDF.
 */
function hexToRgb(hex: string): [number, number, number] {
  const clean = hex.replace('#', '');
  const r = parseInt(clean.substring(0, 2), 16);
  const g = parseInt(clean.substring(2, 4), 16);
  const b = parseInt(clean.substring(4, 6), 16);
  return [r, g, b];
}

/**
 * Format an ISO timestamp into a human-readable string.
 */
function formatDate(iso: string): string {
  try {
    const d = new Date(iso);
    return d.toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true,
    });
  } catch {
    return iso;
  }
}

/**
 * Check if we need a new page, and add one if so.
 * Returns the new Y position (reset to MARGIN_TOP if new page added).
 */
function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > PAGE_HEIGHT - MARGIN_BOTTOM) {
    doc.addPage();
    addPageFooter(doc);
    return MARGIN_TOP;
  }
  return y;
}

/**
 * Add page number footer to the current page.
 */
function addPageFooter(doc: jsPDF): void {
  const pageNum = doc.getNumberOfPages();
  doc.setFontSize(8);
  doc.setTextColor(160, 160, 160);
  doc.text(
    `Page ${pageNum}`,
    PAGE_WIDTH / 2,
    PAGE_HEIGHT - 36,
    { align: 'center' }
  );
  doc.text(
    'Generated by Sunstone PJOS',
    PAGE_WIDTH / 2,
    PAGE_HEIGHT - 26,
    { align: 'center' }
  );
}

/**
 * Fetch an image URL and convert to base64 data URL for jsPDF.
 * Returns null if fetch fails.
 */
async function fetchImageAsBase64(url: string): Promise<string | null> {
  try {
    const response = await fetch(url);
    if (!response.ok) return null;
    const blob = await response.blob();

    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

/**
 * Generate a professional PDF for a signed waiver.
 * Now supports optional logo embedding in the header.
 */
export async function generateWaiverPDF(data: WaiverPDFData): Promise<jsPDF> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'letter',
  });

  const accentColor = data.tenantAccentColor
    ? hexToRgb(data.tenantAccentColor)
    : [238, 119, 67] as [number, number, number]; // default rose-gold accent

  let y = MARGIN_TOP;

  // ── Header: accent color bar ──────────────────────────────────────
  doc.setFillColor(...accentColor);
  doc.rect(0, 0, PAGE_WIDTH, 6, 'F');

  // ── Logo + Tenant name ────────────────────────────────────────────
  let logoInserted = false;
  if (data.tenantLogoUrl) {
    try {
      const logoBase64 = await fetchImageAsBase64(data.tenantLogoUrl);
      if (logoBase64) {
        const format = logoBase64.includes('image/png') ? 'PNG' : 'JPEG';
        const logoSize = 40; // 40pt square
        doc.addImage(logoBase64, format, MARGIN_LEFT, y - 10, logoSize, logoSize);
        // Tenant name to the right of logo
        doc.setFontSize(20);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...accentColor);
        doc.text(data.tenantName, MARGIN_LEFT + logoSize + 12, y + 14);
        y += logoSize + 4;
        logoInserted = true;
      }
    } catch {
      // Logo fetch failed, fall through to text-only header
    }
  }

  if (!logoInserted) {
    // Text-only header (original behavior)
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...accentColor);
    doc.text(data.tenantName, MARGIN_LEFT, y);
    y += 28;
  }

  // ── Subtitle ──────────────────────────────────────────────────────
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80, 80, 80);
  doc.text('Service Waiver', MARGIN_LEFT, y);
  y += 12;

  // ── Divider line ──────────────────────────────────────────────────
  doc.setDrawColor(...accentColor);
  doc.setLineWidth(1.5);
  doc.line(MARGIN_LEFT, y, PAGE_WIDTH - MARGIN_RIGHT, y);
  y += 24;

  // ── Client Information Block ──────────────────────────────────────
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(120, 120, 120);
  doc.text('CLIENT INFORMATION', MARGIN_LEFT, y);
  y += 16;

  const labelX = MARGIN_LEFT;
  const valueX = MARGIN_LEFT + 80;

  const addInfoRow = (label: string, value: string) => {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(140, 140, 140);
    doc.text(label, labelX, y);
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 30);
    doc.text(value, valueX, y);
    y += 16;
  };

  addInfoRow('Name:', data.clientName);
  if (data.clientEmail) addInfoRow('Email:', data.clientEmail);
  if (data.clientPhone) addInfoRow('Phone:', data.clientPhone);
  if (data.eventName) addInfoRow('Event:', data.eventName);
  addInfoRow('Signed:', formatDate(data.signedAt));

  y += 8;

  // ── Thin separator ────────────────────────────────────────────────
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.5);
  doc.line(MARGIN_LEFT, y, PAGE_WIDTH - MARGIN_RIGHT, y);
  y += 20;

  // ── Waiver Text Body ──────────────────────────────────────────────
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(120, 120, 120);
  doc.text('WAIVER AGREEMENT', MARGIN_LEFT, y);
  y += 16;

  doc.setFontSize(10.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(50, 50, 50);

  // Split waiver text into wrapped lines
  const waiverLines = doc.splitTextToSize(data.waiverText, CONTENT_WIDTH);
  const lineHeight = 14;

  for (let i = 0; i < waiverLines.length; i++) {
    y = ensureSpace(doc, y, lineHeight);
    doc.text(waiverLines[i], MARGIN_LEFT, y);
    y += lineHeight;
  }

  y += 16;

  // ── Signature Section ─────────────────────────────────────────────
  y = ensureSpace(doc, y, 120);

  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.5);
  doc.line(MARGIN_LEFT, y, PAGE_WIDTH - MARGIN_RIGHT, y);
  y += 20;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(120, 120, 120);
  doc.text('CLIENT SIGNATURE', MARGIN_LEFT, y);
  y += 16;

  // Embed signature image
  if (data.signatureDataUrl) {
    try {
      const format = data.signatureDataUrl.includes('image/png') ? 'PNG' : 'JPEG';
      const sigWidth = 200;
      const sigHeight = 50;
      doc.addImage(data.signatureDataUrl, format, MARGIN_LEFT, y, sigWidth, sigHeight);
      y += sigHeight + 8;
    } catch (err) {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(180, 180, 180);
      doc.text('[Signature on file]', MARGIN_LEFT, y + 20);
      y += 36;
    }
  }

  // Signature line
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.75);
  doc.line(MARGIN_LEFT, y, MARGIN_LEFT + 240, y);
  y += 14;

  // Signed date below line
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(140, 140, 140);
  doc.text(`Signed: ${formatDate(data.signedAt)}`, MARGIN_LEFT, y);
  y += 8;

  doc.text(data.clientName, MARGIN_LEFT, y);

  // ── Footer on all pages ───────────────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    addPageFooter(doc);
  }

  return doc;
}

/**
 * Generate and trigger browser download of a waiver PDF.
 */
export async function downloadWaiverPDF(data: WaiverPDFData): Promise<void> {
  const doc = await generateWaiverPDF(data);

  // Build filename: waiver-{clientname}-{date}.pdf
  const safeName = data.clientName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  const dateStr = new Date(data.signedAt).toISOString().split('T')[0];
  const filename = `waiver-${safeName}-${dateStr}.pdf`;

  doc.save(filename);
}